### PR TITLE
Merged the changes.

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
I tried using `bluetoothctl` on another distro and works just fine.

### CODE REVIEW

**Comment by CoutHi** [comment]
yes bluetoothctl works fine. 'bluetoothctl paired-devices' however wouldn't work for me. And I think you forgot to add the 'devices' part of the command in the code. You have 'bluetoothctl' but it should be 'bluetoothctl devices'.

**Comment by mgiannopoulos24** [comment]
On both of my distros `bluetoothctl` works by itself. I dont think it needs `devices`. I will add it thought.

**Comment by CoutHi** [comment]
bluetoothctl opens up a whole new session for pairing and finding devices etc. We only need to list what is connected and known to bluetooth to print it out.

**Comment by CoutHi** [comment]
I see you added that now as well. The rest looks good to me as well, nice job and thank you!

**Pull request merged**
